controllers:
    resource: ../../src/Controller/
    type: annotation
controllers_back:
    resource: ../../src/Controller/Back
    type: annotation
    prefix: /admin

controllers_front:
    resource: ../../src/Controller/Front
    type: annotation
    prefix: /

controllers_front_client:
    resource: ../../src/Controller/Front/Client
    type: annotation
    prefix: /

controllers_back_admin:
    resource: ../../src/Controller/Back/Admin
    type: annotation
    prefix: /
